url: https://make-westing.github.io
baseurl: /make-westing

# Site settings
title: Make Westing
email: c.torsday+make-westing@gmail.com
description: "Drinks, Food, Bocce. Oakland's best."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fea936
  secondary: fe5a03
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Glenn Kaplan
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Chris Foott
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/MakeWesting
  - title: facebook
    url: https://www.facebook.com/pages/Make-Westing/202106556499788
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 1741 Telegraph Ave
  - line: Oakland CA, 94612

# Build settings
markdown: kramdown
permalink: pretty
